#!/usr/bin/env bash
# This is a bash script that displays the content of the file /etc/passwrd:
#   username
#   user id
#   Home directory path for the user

FILE="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$FILE"
