#!/usr/bin/env bash
# This is a Bash script that displays:
#   The content of the current directory In a list format
#   Where only the part of the name after the first dash is displayed

LIST=$(ls)

for i in $LIST; 
do
	echo "$i" | cut -d '-' -f2
done
