#!/usr/bin/env bash
#Let’s install the ufw firewall and setup a few rules on web-01.
#
# Requirements:
#
# Configure ufw so that it blocks all incoming traffic, except
# ##### the following TCP ports:
#       22 (SSH)
#       443 (HTTPS SSL)
#       80 (HTTP)
sudo apt install ufw 
# ##########set the defaults used by UFW#######
sudo ufw default deny incoming
sudo ufw default allow outgoing
# #########Configure Firewall#################
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
