#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
#
# Requirements:
#
#   Your Bash script must be 7 lines long or less
#   There must be a new line at the end of the file
#   You respect Bash script requirements
#   You cannot use ;
#   You cannot use &&
#   You cannot use wget
#   You cannot execute your previous answer file 
#	(Do not include the name of the previous script in this one)
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start

